/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3EFIREBASE_AUTODEFS_H
#define S3EFIREBASE_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_FIREBASE_NAME "s3eFirebase"
#define S3E_EXT_FIREBASE_HASH 0x5d679b71

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("s3eFirebase", 1)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !S3EFIREBASE_AUTODEFS_H */
