/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/**
 * Definitions for functions types passed to/from s3eExt interface
 */
typedef       void(*s3eFirebaseInitialize_t)();

/**
 * struct that gets filled in by s3eFirebaseRegister
 */
typedef struct s3eFirebaseFuncs
{
    s3eFirebaseInitialize_t m_s3eFirebaseInitialize;
} s3eFirebaseFuncs;
